version: '3.8'

services:
  # The API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map port 8080 on your machine to port 8080 in the container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      # The connection string now points to the 'db' service name
      - ConnectionStrings__DefaultConnection=Host=db;Database=LeagueDb;Username=postgres;Password=${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

  # The Database Service
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=LeagueDb
    ports:
      - "5433:5432" # Keep exposing the DB on 5433 locally for tools like DBeaver
    volumes:
      - leaguedb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d LeagueDb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  leaguedb-data:
